Use -fsanitize-link-c++-runtime instead of -lubsan
robinlinden/hastur pull request #124
Opened 2021-12-26 14:04 UTC by johnor

* See: https://github.com/bazelbuild/bazel/issues/11122
* Using explicit lubsan should be avaided, see:
  https://groups.google.com/g/address-sanitizer/c/SD590XDinfQ/m/NMUPj_G0BgAJ

2021-12-26 16:25 UTC, robinlinden commented
Typo in commit message, `avaided` -> `avoided`. Did you have issues linking with the ubsan config?

2021-12-26 19:14 UTC, robinlinden requested changes
Commit title also needs to be prefixed with the area it worked on to follow the convention. `build: Use -fsan...`

2021-12-27 08:53 UTC, johnor commented
> 



> Typo in commit message, `avaided` -> `avoided`. Did you have issues linking with the ubsan config?

Didn't have any issues, just saw that -lubsan should be avoided.

2021-12-27 14:26 UTC, robinlinden approved these changes

2021-12-27 15:27 UTC, merged