Add dependency on icu
robinlinden/hastur pull request #506
Opened 2023-02-25 00:09 UTC by Zer0-One

icu will handle IDNA and misc unicode stuff that requires lugging around giant mapping tables that need to stay up-to-date with the unicode standard.

2023-02-26 21:24 UTC, robinlinden requested changes
We're getting ~40k lines of warnings like 
```
In file included from external/icu/source/common/ubidiwrt.cpp:23:
In file included from external/icu/source/common/unicode/ustring.h:22:
external/icu/source/common/unicode/putil.h(29,10): warning: #include resolved using non-portable Microsoft search rules as: external/icu/source/common/unicode/utypes.h [-Wmicrosoft-include]
#include "unicode/utypes.h"
         ^
```
in the clang-cl ci build, so that's something we need to look at before merging this. :P Maybe just an `includes = ["source/common"]` or something that's needed, haven't seen that warning before.

2023-02-26 21:24 UTC, robinlinden commented on WORKSPACE
> +    name = "icu",  # Unicode Inc
License should be the SPDX identifier.

2023-02-26 21:24 UTC, robinlinden commented on third_party/icu.BUILD
> +    linkopts = ["-ldl"],
`-ldl` only on Linux.

2023-02-27 01:50 UTC, Zer0-One commented
`cl : Command line error D8021 : invalid numeric argument '/Wno-microsoft-include'`

I can't figure out how to shut the compiler up about that warning.

2023-02-27 03:06 UTC, Zer0-One commented
Warnings fixed

2023-02-27 08:22 UTC, robinlinden approved these changes
Looks good!

2023-02-27 08:22 UTC, merged